import {
  Activity, AlertCircle, AlertTriangle,
  ArrowDown, ArrowDownCircle, ArrowDownLeft, ArrowLeft, ArrowRight, ArrowRightCircle,
  ArrowUpCircle, ArrowUpRight,
  BarChart2, Bell, Briefcase, Calendar, Camera, Check, CheckCircle,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, Compass, Cpu,
  CreditCard, DollarSign, Download, Edit, Edit2, Edit3,
  ExternalLink, Eye, Feather, FileText, Globe, Grid,
  Headphones, Home, Inbox, Info, Link, List, Lock, LogOut,
  MapPin, MessageCircle, Minus, MinusCircle, Moon, MoreHorizontal, MoreVertical,
  Package, Phone, PieChart, PlayCircle, Plus, PlusCircle,
  RefreshCw, Search, Send, Server, Share, Share2,
  Shield, ShieldOff, ShoppingBag, ShoppingCart,
  Sliders, Smile, Star, Sun, Tag, TrendingUp,
  Upload, UploadCloud, User, UserCheck, UserPlus, Users,
  Wallet, X, XCircle, Zap,
} from "lucide-react-native";
import React from "react";

const MAP: Record<string, React.ComponentType<any>> = {
  "activity":        Activity,
  "alert-circle":    AlertCircle,
  "alert-triangle":  AlertTriangle,
  "arrow-down":      ArrowDown,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-down-left":  ArrowDownLeft,
  "arrow-left":      ArrowLeft,
  "arrow-right":     ArrowRight,
  "arrow-right-circle": ArrowRightCircle,
  "arrow-up-circle": ArrowUpCircle,
  "arrow-up-right":  ArrowUpRight,
  "bar-chart-2":     BarChart2,
  "bell":            Bell,
  "briefcase":       Briefcase,
  "calendar":        Calendar,
  "camera":          Camera,
  "check":           Check,
  "check-circle":    CheckCircle,
  "chevron-down":    ChevronDown,
  "chevron-left":    ChevronLeft,
  "chevron-right":   ChevronRight,
  "chevron-up":      ChevronUp,
  "clock":           Clock,
  "compass":         Compass,
  "cpu":             Cpu,
  "credit-card":     CreditCard,
  "delete":          X,
  "dollar-sign":     DollarSign,
  "download":        Download,
  "edit":            Edit,
  "edit-2":          Edit2,
  "edit-3":          Edit3,
  "external-link":   ExternalLink,
  "eye":             Eye,
  "feather":         Feather,
  "file-text":       FileText,
  "globe":           Globe,
  "grid":            Grid,
  "headphones":      Headphones,
  "home":            Home,
  "inbox":           Inbox,
  "info":            Info,
  "key":             Lock,
  "link":            Link,
  "list":            List,
  "lock":            Lock,
  "log-out":         LogOut,
  "map-pin":         MapPin,
  "moon":            Moon,
  "message-circle":  MessageCircle,
  "minus":           Minus,
  "minus-circle":    MinusCircle,
  "more-horizontal": MoreHorizontal,
  "more-vertical":   MoreVertical,
  "package":         Package,
  "phone":           Phone,
  "pie-chart":       PieChart,
  "play-circle":     PlayCircle,
  "plus":            Plus,
  "plus-circle":     PlusCircle,
  "refresh-cw":      RefreshCw,
  "search":          Search,
  "send":            Send,
  "server":          Server,
  "share":           Share,
  "share-2":         Share2,
  "shield":          Shield,
  "shield-off":      ShieldOff,
  "shopping-bag":    ShoppingBag,
  "shopping-cart":   ShoppingCart,
  "sliders":         Sliders,
  "smile":           Smile,
  "star":            Star,
  "sun":             Sun,
  "tag":             Tag,
  "trending-up":     TrendingUp,
  "upload":          Upload,
  "upload-cloud":    UploadCloud,
  "user":            User,
  "user-check":      UserCheck,
  "user-plus":       UserPlus,
  "users":           Users,
  "wallet":          Wallet,
  "x":               X,
  "x-circle":        XCircle,
  "zap":             Zap,
};

type FeatherName = keyof typeof MAP;

interface IconProps {
  name: FeatherName | string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: any;
}

export default function Icon({ name, size = 20, color = "#000", strokeWidth = 2, style }: IconProps) {
  const Component = MAP[name] ?? AlertCircle;
  return <Component size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
