import { Product } from '@/components/MarketplaceCard';

export const MARKETPLACE_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: '10kg White Maize Meal',
    description: 'Bulk white maize meal, perfect for stokvels',
    price: 89,
    unit: '10kg bag',
    minOrder: 5,
    retailer: 'Shoprite',
    category: 'Staples',
    discount: 15,
    featured: true,
    savings: 75,
  },
  {
    id: 'p2',
    name: 'Sunflower Cooking Oil 5L',
    description: 'Premium sunflower cooking oil, bulk pack',
    price: 119,
    unit: '5L bottle',
    minOrder: 4,
    retailer: 'Pick n Pay',
    category: 'Oils',
    discount: 10,
    savings: 52,
  },
  {
    id: 'p3',
    name: 'Long Grain White Rice 10kg',
    description: 'Premium long grain parboiled rice',
    price: 149,
    unit: '10kg bag',
    minOrder: 4,
    retailer: 'Shoprite',
    category: 'Staples',
    featured: true,
  },
  {
    id: 'p4',
    name: 'Sugar 10kg',
    description: 'White granulated sugar',
    price: 139,
    unit: '10kg bag',
    minOrder: 3,
    retailer: 'Spar',
    category: 'Staples',
    discount: 8,
    savings: 30,
  },
  {
    id: 'p5',
    name: 'Washing Powder 4kg',
    description: 'Bio-enzyme laundry detergent powder',
    price: 79,
    unit: '4kg box',
    minOrder: 6,
    retailer: 'Checkers',
    category: 'Cleaning',
    discount: 20,
    savings: 95,
  },
  {
    id: 'p6',
    name: 'Canola Oil 750ml x 12',
    description: 'Heart-healthy canola oil multipack',
    price: 249,
    unit: '12-pack',
    minOrder: 2,
    retailer: 'Woolworths',
    category: 'Oils',
  },
  {
    id: 'p7',
    name: 'Canned Tomatoes x 24',
    description: 'Peeled canned tomatoes, bulk case',
    price: 189,
    unit: '24 x 410g',
    minOrder: 2,
    retailer: 'Pick n Pay',
    category: 'Canned Goods',
    discount: 12,
    savings: 45,
  },
  {
    id: 'p8',
    name: 'Pasta 5kg',
    description: 'Spaghetti & penne mixed bulk pack',
    price: 69,
    unit: '5kg pack',
    minOrder: 4,
    retailer: 'Shoprite',
    category: 'Staples',
  },
  {
    id: 'p9',
    name: 'Bar Soap x 48',
    description: 'Classic bath soap, value multipack',
    price: 219,
    unit: '48-pack 150g',
    minOrder: 2,
    retailer: 'Checkers',
    category: 'Personal Care',
    discount: 25,
    featured: true,
    savings: 110,
  },
  {
    id: 'p10',
    name: 'Chicken Braai Pack 5kg',
    description: 'Frozen mixed braai chicken portions',
    price: 199,
    unit: '5kg pack',
    minOrder: 3,
    retailer: 'Pick n Pay',
    category: 'Meat & Poultry',
    discount: 18,
    savings: 80,
  },
];

export const CATEGORIES = ['All', 'Staples', 'Oils', 'Canned Goods', 'Cleaning', 'Personal Care', 'Meat & Poultry'];

export const RETAILERS = [
  { name: 'Shoprite',   color: '#D7282F', featured: true,  logo: require('../assets/images/retailers/shoprite.png') },
  { name: 'Pick n Pay', color: '#1B3D79', featured: true,  logo: require('../assets/images/retailers/picknpay.jpg') },
  { name: 'Checkers',   color: '#00A79D', featured: false, logo: require('../assets/images/retailers/checkers.jpg') },
  { name: 'Spar',       color: '#007A2E', featured: false, logo: require('../assets/images/retailers/spar.jpg') },
  { name: 'Woolworths', color: '#1A1A1A', featured: false, logo: require('../assets/images/retailers/woolworths.png') },
];
