import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  Platform, Share, Alert,
} from 'react-native';
import Icon from '@/components/Icon';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Haptics from 'expo-haptics';

import { useColors } from '@/hooks/useColors';
import { useStokvel, VEHICLE_META, InvestmentVehicle } from '@/context/StokvelContext';

const TAX_YEAR     = '2025/2026';
const TAX_THRESHOLD = 23_800;
const BANK_RATE     = 5.0;

/* ─── helpers ─────────────────────────────────────────── */
function fmt(n: number) {
  return `R ${n.toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function StatusPill({ text, color }: { text: string; color: string }) {
  return (
    <View style={[pill.wrap, { backgroundColor: color + '18', borderColor: color + '40' }]}>
      <Text style={[pill.txt, { color }]}>{text}</Text>
    </View>
  );
}
const pill = StyleSheet.create({
  wrap: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10, borderWidth: 1 },
  txt:  { fontSize: 11, fontWeight: '700' },
});

/* ─── Section wrapper ─────────────────────────────────── */
function Section({ title, children, colors }: { title: string; children: React.ReactNode; colors: any }) {
  return (
    <View style={[sec.wrap, { backgroundColor: colors.card }]}>
      <Text style={[sec.title, { color: colors.foreground }]}>{title}</Text>
      {children}
    </View>
  );
}
const sec = StyleSheet.create({
  wrap:  { borderRadius: 16, padding: 16, gap: 12 },
  title: { fontSize: 15, fontWeight: '700', marginBottom: -4 },
});

/* ═══════════════════════════════════════════════════════
   MAIN TAX REPORT SCREEN
═══════════════════════════════════════════════════════ */
export default function TaxReportScreen() {
  const { id }   = useLocalSearchParams<{ id: string }>();
  const colors   = useColors();
  const insets   = useSafeAreaInsets();
  const router   = useRouter();
  const { stokvels } = useStokvel();
  const [selectedMember, setSelectedMember] = useState<string | null>(null);

  const stokvel = stokvels.find((s) => s.id === id);
  const topPad  = Platform.OS === 'web' ? 67 : insets.top;

  if (!stokvel || stokvel.type !== 'investment' || !stokvel.investmentConfig) {
    return (
      <View style={{ flex: 1, backgroundColor: colors.background, justifyContent: 'center', alignItems: 'center' }}>
        <Text style={{ color: colors.mutedForeground }}>No investment data available.</Text>
        <TouchableOpacity onPress={() => router.back()}><Text style={{ color: colors.primary, marginTop: 8 }}>Go Back</Text></TouchableOpacity>
      </View>
    );
  }

  const cfg     = stokvel.investmentConfig!;
  const vehicle = cfg.vehicle as InvestmentVehicle;
  const vm      = VEHICLE_META[vehicle];
  const midRate = (vm.minReturn + vm.maxReturn) / 2;

  /* ── Per-member calculations ── */
  const monthsActive = Math.max(1, Math.round(
    (new Date().getTime() - new Date(stokvel.createdAt).getTime()) / (30 * 24 * 60 * 60 * 1000)
  ));
  const principal = stokvel.totalSaved;
  const members   = stokvel.members.length;

  const grossInterest    = principal * (midRate / 100) * (monthsActive / 12);
  const platformFees     = grossInterest * (cfg.platformFeePercent / 100);
  const netInterest      = grossInterest - platformFees;
  const perMemberGross   = grossInterest / members;
  const perMemberFee     = platformFees / members;
  const perMemberNet     = netInterest / members;
  const perMemberTaxable = Math.max(0, perMemberNet - TAX_THRESHOLD);

  /* ── Share/export ── */
  const handleExport = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    const lines = [
      `StockFair — SARS Tax Report`,
      `Tax Year: ${TAX_YEAR}`,
      `Stokvel: ${stokvel.name}`,
      `Investment Vehicle: ${vm.label}`,
      `Reference Rate: ${midRate}% p.a.`,
      `Months Active: ${monthsActive}`,
      ``,
      `GROUP TOTALS`,
      `Gross Interest: ${fmt(grossInterest)}`,
      `Platform Fees: ${fmt(platformFees)}`,
      `Net Interest: ${fmt(netInterest)}`,
      ``,
      `PER MEMBER`,
      `Gross Interest: ${fmt(perMemberGross)}`,
      `Platform Fee: ${fmt(perMemberFee)}`,
      `Net Interest: ${fmt(perMemberNet)}`,
      `Tax-free Exemption (S10(1)(i)): R ${TAX_THRESHOLD.toLocaleString('en-ZA')}`,
      `Taxable Amount: ${fmt(perMemberTaxable)}`,
      ``,
      `Members:`,
      ...stokvel.members.map((m) => `  ${m.name}: ${fmt(perMemberNet)} net interest`),
      ``,
      `Generated by StockFair · ${new Date().toLocaleDateString('en-ZA')}`,
      `For use with SARS ITR12 — Line: "Local Interest"`,
    ];
    try {
      await Share.share({ message: lines.join('\n'), title: `StockFair Tax Report — ${stokvel.name}` });
    } catch {}
  };

  const filteredMembers = selectedMember
    ? stokvel.members.filter((m) => m.id === selectedMember)
    : stokvel.members;

  return (
    <View style={{ flex: 1, backgroundColor: colors.background }}>
      {/* Header */}
      <View style={[s.header, { paddingTop: topPad + 10, backgroundColor: colors.foreground }]}>
        <TouchableOpacity style={s.backBtn} onPress={() => router.back()}>
          <Icon name="arrow-left" size={22} color={colors.background} />
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={[s.headerTitle, { color: colors.background }]}>SARS Tax Report</Text>
          <Text style={[s.headerSub, { color: colors.background + '80' }]}>{stokvel.name} · {TAX_YEAR}</Text>
        </View>
        <TouchableOpacity style={[s.exportBtn, { backgroundColor: colors.background + '18' }]} onPress={handleExport}>
          <Icon name="download" size={18} color={colors.background} />
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.body} showsVerticalScrollIndicator={false}>

        {/* ── Report header card ── */}
        <View style={[s.reportHeader, { backgroundColor: colors.card }]}>
          <View style={s.reportHeaderRow}>
            <View style={[s.reportIconWrap, { backgroundColor: '#16A34A18' }]}>
              <Icon name="file-text" size={24} color="#16A34A" />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[s.reportTitle, { color: colors.foreground }]}>Interest Income Statement</Text>
              <Text style={[s.reportSub, { color: colors.mutedForeground }]}>
                {vm.label} · Tax Year {TAX_YEAR}
              </Text>
            </View>
          </View>
          <View style={[s.reportMeta, { borderTopColor: colors.border }]}>
            {[
              { label: 'Reference Rate',  value: `${midRate}% p.a.` },
              { label: 'Period',          value: `${monthsActive} months` },
              { label: 'Platform Fee',    value: `${cfg.platformFeePercent}%` },
              { label: 'Report Date',     value: new Date().toLocaleDateString('en-ZA') },
            ].map((row) => (
              <View key={row.label} style={s.reportMetaItem}>
                <Text style={[s.reportMetaLabel, { color: colors.mutedForeground }]}>{row.label}</Text>
                <Text style={[s.reportMetaValue, { color: colors.foreground }]}>{row.value}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* ── Group totals ── */}
        <Section title="Group Interest Summary" colors={colors}>
          {[
            { label: 'Gross interest earned',       value: fmt(grossInterest),   color: colors.foreground },
            { label: `Platform fees (${cfg.platformFeePercent}%)`, value: `−${fmt(platformFees)}`, color: '#DC2626' },
            { label: 'Net interest to members',     value: fmt(netInterest),     color: '#16A34A', bold: true },
          ].map((row, i) => (
            <View key={row.label} style={[s.summaryRow, i > 0 && { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }]}>
              <Text style={[s.summaryLabel, { color: colors.mutedForeground }]}>{row.label}</Text>
              <Text style={[s.summaryValue, { color: row.color, fontWeight: row.bold ? '800' : '600', fontSize: row.bold ? 17 : 14 }]}>{row.value}</Text>
            </View>
          ))}
        </Section>

        {/* ── Tax threshold ── */}
        <Section title="SARS Exemption — Section 10(1)(i)" colors={colors}>
          <View style={[s.exemptionBox, { backgroundColor: '#16A34A0F', borderColor: '#16A34A30' }]}>
            <Icon name="shield" size={18} color="#16A34A" />
            <View style={{ flex: 1 }}>
              <Text style={[s.exemptionTitle, { color: '#16A34A' }]}>R {TAX_THRESHOLD.toLocaleString('en-ZA')} Interest Exemption</Text>
              <Text style={[s.exemptionBody, { color: colors.mutedForeground }]}>
                South African resident individuals are exempt from tax on the first R23,800 of interest income per tax year.
              </Text>
            </View>
          </View>

          {[
            { label: 'Net interest per member (est.)', value: fmt(perMemberNet), color: colors.foreground },
            { label: 'Less: S10(1)(i) exemption',     value: `(${fmt(Math.min(perMemberNet, TAX_THRESHOLD))})`, color: '#16A34A' },
            { label: 'Taxable interest (if any)',      value: fmt(perMemberTaxable), color: perMemberTaxable > 0 ? '#DC2626' : '#16A34A', bold: true },
          ].map((row, i) => (
            <View key={row.label} style={[s.summaryRow, i > 0 && { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }]}>
              <Text style={[s.summaryLabel, { color: colors.mutedForeground }]}>{row.label}</Text>
              <Text style={[s.summaryValue, { color: row.color, fontWeight: row.bold ? '800' : '600', fontSize: row.bold ? 17 : 14 }]}>{row.value}</Text>
            </View>
          ))}

          {perMemberTaxable > 0 ? (
            <View style={[s.warningBox, { backgroundColor: '#DC262612', borderColor: '#DC262630' }]}>
              <Icon name="alert-triangle" size={14} color="#DC2626" />
              <Text style={[s.warningTxt, { color: '#DC2626' }]}>
                Declare {fmt(perMemberTaxable)} under "Local Interest" on your ITR12. This report serves as your supporting document.
              </Text>
            </View>
          ) : (
            <View style={[s.okBox, { backgroundColor: '#16A34A12', borderColor: '#16A34A30' }]}>
              <Icon name="check-circle" size={14} color="#16A34A" />
              <Text style={[s.okTxt, { color: '#16A34A' }]}>
                Your interest income is within the R23,800 exemption. No declaration needed — keep this report for 5 years.
              </Text>
            </View>
          )}
        </Section>

        {/* ── Member filter ── */}
        <View style={s.filterRow}>
          <Text style={[s.filterLabel, { color: colors.mutedForeground }]}>Filter by member</Text>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingRight: 20 }}>
            <TouchableOpacity
              style={[s.filterChip, { backgroundColor: selectedMember === null ? colors.primary : colors.card, borderColor: selectedMember === null ? colors.primary : colors.border }]}
              onPress={() => setSelectedMember(null)}
            >
              <Text style={[s.filterChipTxt, { color: selectedMember === null ? colors.primaryForeground : colors.mutedForeground }]}>All</Text>
            </TouchableOpacity>
            {stokvel.members.map((m) => (
              <TouchableOpacity key={m.id}
                style={[s.filterChip, { backgroundColor: selectedMember === m.id ? colors.primary : colors.card, borderColor: selectedMember === m.id ? colors.primary : colors.border }]}
                onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); setSelectedMember(m.id); }}
              >
                <Text style={[s.filterChipTxt, { color: selectedMember === m.id ? colors.primaryForeground : colors.mutedForeground }]}>{m.name.split(' ')[0]}</Text>
              </TouchableOpacity>
            ))}
          </ScrollView>
        </View>

        {/* ── Per-member table ── */}
        <Section title="Member Interest Certificates" colors={colors}>
          <Text style={[s.tableSub, { color: colors.mutedForeground }]}>For ITR12 submission — retain for 5 years</Text>
          {filteredMembers.map((m, i) => {
            const taxable = Math.max(0, perMemberNet - TAX_THRESHOLD);
            const isOver  = taxable > 0;
            return (
              <View key={m.id} style={[s.memberCert, { borderColor: colors.border, backgroundColor: m.id === 'me' ? colors.primary + '08' : colors.background }]}>
                <View style={s.certHeader}>
                  <View style={[s.certAvatar, { backgroundColor: m.id === 'me' ? '#16A34A' : colors.muted }]}>
                    <Text style={[s.certInitial, { color: m.id === 'me' ? '#fff' : colors.mutedForeground }]}>
                      {m.name.split(' ').map((w) => w[0]).join('').slice(0, 2).toUpperCase()}
                    </Text>
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[s.certName, { color: colors.foreground }]}>{m.name}{m.id === 'me' ? ' (You)' : ''}</Text>
                    <Text style={[s.certSub, { color: colors.mutedForeground }]}>Position #{m.position}</Text>
                  </View>
                  <StatusPill
                    text={isOver ? 'Declare to SARS' : 'Within Exemption'}
                    color={isOver ? '#DC2626' : '#16A34A'}
                  />
                </View>

                <View style={[s.certTable, { borderTopColor: colors.border }]}>
                  {[
                    { label: 'Gross interest income',          value: fmt(perMemberGross) },
                    { label: `Less: platform fee (${cfg.platformFeePercent}%)`, value: `(${fmt(perMemberFee)})` },
                    { label: 'Net interest income',            value: fmt(perMemberNet), highlight: true },
                    { label: 'Less: S10(1)(i) exemption',     value: `(${fmt(Math.min(perMemberNet, TAX_THRESHOLD))})` },
                    { label: 'Taxable amount (ITR12 Line)',    value: fmt(taxable), highlight: true, warn: isOver },
                  ].map((row) => (
                    <View key={row.label} style={[s.certRow, { borderTopColor: colors.border }]}>
                      <Text style={[s.certRowLabel, { color: colors.mutedForeground }]}>{row.label}</Text>
                      <Text style={[s.certRowValue, {
                        color: row.warn ? '#DC2626' : row.highlight ? '#16A34A' : colors.foreground,
                        fontWeight: row.highlight ? '800' : '500',
                      }]}>{row.value}</Text>
                    </View>
                  ))}
                </View>

                <View style={[s.itrlLine, { backgroundColor: isOver ? '#DC262610' : '#16A34A10', borderColor: isOver ? '#DC262630' : '#16A34A30' }]}>
                  <Icon name="file-text" size={13} color={isOver ? '#DC2626' : '#16A34A'} />
                  <Text style={[s.itrlTxt, { color: isOver ? '#DC2626' : '#16A34A' }]}>
                    {isOver
                      ? `ITR12 → Local Interest = ${fmt(taxable)}`
                      : 'ITR12 → Local Interest = R 0.00 (fully exempt)'}
                  </Text>
                </View>
              </View>
            );
          })}
        </Section>

        {/* ── Important notes ── */}
        <View style={[s.notesCard, { backgroundColor: colors.card }]}>
          <Text style={[s.notesTitle, { color: colors.foreground }]}>Important Notes</Text>
          {[
            'This report is for informational purposes. Consult a tax professional for advice specific to your situation.',
            'Interest income must be declared in the tax year it was received, not when contributed.',
            'Married in community of property? The R23,800 exemption applies to each spouse individually.',
            'Keep this report and any supporting bank statements for at least 5 years.',
            'StockFair is not a registered financial services provider under the FSCA.',
          ].map((note, i) => (
            <View key={i} style={s.noteRow}>
              <View style={[s.noteDot, { backgroundColor: colors.mutedForeground }]} />
              <Text style={[s.noteTxt, { color: colors.mutedForeground }]}>{note}</Text>
            </View>
          ))}
        </View>

        {/* ── Export button ── */}
        <TouchableOpacity style={[s.exportFullBtn, { backgroundColor: colors.foreground }]} onPress={handleExport}>
          <Icon name="share-2" size={18} color={colors.background} />
          <Text style={[s.exportFullTxt, { color: colors.background }]}>Share / Export Tax Report</Text>
        </TouchableOpacity>

        <Text style={[s.footer, { color: colors.mutedForeground }]}>
          Generated by StockFair · {new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })}
        </Text>
      </ScrollView>
    </View>
  );
}

/* ─── Styles ──────────────────────────────────────────── */
const s = StyleSheet.create({
  header:       { paddingHorizontal: 20, paddingBottom: 16, flexDirection: 'row', alignItems: 'center', gap: 12 },
  backBtn:      { width: 40, height: 40, justifyContent: 'center' },
  headerTitle:  { fontSize: 18, fontWeight: '700' },
  headerSub:    { fontSize: 12, marginTop: 2 },
  exportBtn:    { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },

  body:         { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 40, gap: 12 },

  reportHeader:  { borderRadius: 16, padding: 16, gap: 14 },
  reportHeaderRow:{ flexDirection: 'row', alignItems: 'center', gap: 14 },
  reportIconWrap: { width: 52, height: 52, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  reportTitle:   { fontSize: 16, fontWeight: '700' },
  reportSub:     { fontSize: 12, marginTop: 3 },
  reportMeta:    { flexDirection: 'row', flexWrap: 'wrap', gap: 12, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 14 },
  reportMetaItem:{ minWidth: '40%' },
  reportMetaLabel:{ fontSize: 11, marginBottom: 2 },
  reportMetaValue:{ fontSize: 13, fontWeight: '700' },

  summaryRow:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10 },
  summaryLabel:  { fontSize: 13 },
  summaryValue:  { fontSize: 14, fontWeight: '600' },

  exemptionBox:  { flexDirection: 'row', gap: 12, padding: 12, borderRadius: 12, borderWidth: 1, alignItems: 'flex-start' },
  exemptionTitle:{ fontSize: 13, fontWeight: '700', marginBottom: 4 },
  exemptionBody: { fontSize: 12, lineHeight: 17 },

  warningBox:    { flexDirection: 'row', gap: 8, padding: 12, borderRadius: 12, borderWidth: 1, alignItems: 'flex-start' },
  warningTxt:    { flex: 1, fontSize: 12, lineHeight: 17 },
  okBox:         { flexDirection: 'row', gap: 8, padding: 12, borderRadius: 12, borderWidth: 1, alignItems: 'flex-start' },
  okTxt:         { flex: 1, fontSize: 12, lineHeight: 17 },

  filterRow:     { gap: 8 },
  filterLabel:   { fontSize: 12, fontWeight: '600', paddingHorizontal: 0 },
  filterChip:    { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1 },
  filterChipTxt: { fontSize: 13, fontWeight: '600' },

  tableSub:      { fontSize: 12 },
  memberCert:    { borderRadius: 14, borderWidth: 1, padding: 14, gap: 12 },
  certHeader:    { flexDirection: 'row', alignItems: 'center', gap: 10 },
  certAvatar:    { width: 38, height: 38, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  certInitial:   { fontSize: 13, fontWeight: '700' },
  certName:      { fontSize: 14, fontWeight: '700' },
  certSub:       { fontSize: 11, marginTop: 2 },
  certTable:     { gap: 0, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 10 },
  certRow:       { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 7, borderTopWidth: StyleSheet.hairlineWidth },
  certRowLabel:  { fontSize: 12, flex: 1, paddingRight: 8 },
  certRowValue:  { fontSize: 13 },
  itrlLine:      { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 10, borderRadius: 10, borderWidth: 1 },
  itrlTxt:       { fontSize: 12, fontWeight: '700' },

  notesCard:     { borderRadius: 14, padding: 16, gap: 10 },
  notesTitle:    { fontSize: 14, fontWeight: '700' },
  noteRow:       { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
  noteDot:       { width: 4, height: 4, borderRadius: 2, marginTop: 7 },
  noteTxt:       { flex: 1, fontSize: 12, lineHeight: 17 },

  exportFullBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, padding: 18, borderRadius: 14 },
  exportFullTxt: { fontSize: 15, fontWeight: '700' },
  footer:        { textAlign: 'center', fontSize: 11, marginTop: 4, paddingBottom: 8 },
});
